FROM rockylinux:8 
ENV container docker

RUN dnf  -y update
RUN dnf clean all
RUN dnf -y install systemd;

RUN (cd /lib/systemd/system/sysinit.target.wants/; for i in ; do [ $i == systemd-tmpfiles-setup.service ] || rm -f $i; done);

RUN rm -rf /lib/systemd/system/multi-user.target.wants/ \
&& rm -rf /etc/systemd/system/.wants/ \
&& rm -rf /lib/systemd/system/local-fs.target.wants/ \
&& rm -f /lib/systemd/system/sockets.target.wants/udev \
&& rm -f /lib/systemd/system/sockets.target.wants/initctl \
&& rm -rf /lib/systemd/system/basic.target.wants/ \
&& rm -f /lib/systemd/system/anaconda.target.wants/*

RUN dnf -y install vim nc cronie wget yum-utils curl iproute net-tools traceroute

RUN dnf -y install httpd

RUN dnf module reset nodejs && dnf module -y enable nodejs:20 && dnf module -y install nodejs:20

RUN dnf clean all

RUN dnf -y update

RUN systemctl enable httpd.service

RUN systemctl enable crond.service

CMD ["/usr/sbin/init"]
