version: '3.9'
services:
 consolidainfoarchivos_apache:
  build:
   context: /var/lib/docker/volumes/pr_consolidainfoarchivos_documentroot/_data/consolidainfo/backend
   dockerfile: Dockerfile
  image: consolidainfoarchivos_apache:latest
  container_name: consolidainfoarchivos_apache
  hostname: consolidainfoarchivosdocker
  restart: always
  privileged: true
  volumes:
    - type: volume
      source: documentroot
      target: /var/www/html
    - type: volume
      source: apacheconfig
      target: /etc/httpd
    - /sys/fs/cgroup:/sys/fs/cgroup:ro
    - /etc/localtime:/etc/localtime:ro
  networks:
    consolidainfoarchivos:
     ipv4_address: 192.168.250.50
  ports:
   - "15106:3080"
  expose:
   - 15106

volumes:
 documentroot:
 apacheconfig:

networks:
  consolidainfoarchivos:
    name: consolidainfoarchivos
    driver: bridge
    enable_ipv6: false
    ipam:
      driver: default
      config:
        - subnet: 192.168.250.48/29
          gateway: 192.168.250.49
