INSERT INTO Vacantes_Vigentes_Completo (CODIGO_VACANTE,TITULO_VACANTE,DESCRIPCION_VACANTE,NIVEL_ESTUDIOS,DISCIPLINA_PROFESION,SALARIO_INGRESO,RANGO_SALARIAL,CANTIDAD_VACANTES,CARGO,TIPO_DOCUMENTO_EMPLEADOR,NUMERO_IDENTIFICACION_EMPLEADOR,NOMBRE_EMPLEADOR,SOLICITUD_EXCEPCION_PUBLICACION,FECHA_PUBLICACION,FECHA_VENCIMIENTO,REGION,DEPARTAMENTO,MUNICIPIO,SECTOR_ECONOMICO,TIPO_CONTRATO,TELETRABAJO,DISCAPACIDAD,URL_DETALLE_VACANTE,NOMBRE_PRESTADOR,TIPO_PRESTADOR,DIRECTORIO_ORIGEN,PLATAFORMA,PUBLICOPRIVADO,EMPLEADOR,MESES_EXPERIENCIA_CARGO,FECHA_CREACION,PUNTO_ATENCION,HIDROCARBUROS,PLAZA_PRACTICA,BUSQUEDA)
VALUES ('PP202310-21',
'PL- APRENDIZ',
'TOMA DE MUESTRAS, PROCESOS DE ANÃ�LISIS, MANEJO DE EQUIPOS.',
'Universitarios',
'QUIMICA-TECNOLOGIA EN ALIMENTOS',
'1530000',
'$1.500.001 - $2.000.000',
2,
'2113',
'Número de Identificación Tributaria',
'8903016903',
'Ingredion',
'N',
'2023-10-05T00:00:00.000Z',
'2023-10-30T00:00:00.000Z',
'Región Pacífico',
'VALLE DEL CAUCA',
'CALI',
'1089',
'Otra',
0,
0,
'https://sige.univalle.edu.co/site/joboffers/997',
'UNIVERSIDAD DEL VALLE',
'BOLSA',
'\10.250.0.10\e$\FTP\FTPRoot\LocalUser\univalle',
'UNIVERSIDAD DEL VALLE',
2,
'INGREDION COLOMBIA S.A',
0,
'2023-10-18T03:00:10.960Z',
'UNIVERSIDAD DEL VALLE',
0,
1,
'PP202310-21 UNIVERSIDAD DEL VALLE TOMA DE MUESTRAS, PROCESOS DE ANÃ�LISIS, MANEJO DE EQUIPOS. PL- APRENDIZ'
)



-- Crear tabla de suscripciones

CREATE TABLE Suscripciones (
    Id INT PRIMARY KEY IDENTITY(1,1),
    Nombre NVARCHAR(255) NOT NULL,
    Correo NVARCHAR(255) NOT NULL,
    Celular NVARCHAR(20)
);

-- Crear tabla de Visitas

CREATE TABLE Visitas (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Fecha DATE UNIQUE,
    VisitasDiarias INT DEFAULT 0
);

-- Crear tabla de Vacantes consultadas

CREATE TABLE Vacantes_Consultadas (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    FechaHoraConsulta DATETIME NOT NULL,
    CodigoVacante VARCHAR(255) NOT NULL
);
